version: '2.1'
services:
  live-reload:
    image: spotify-radio
    build: .
    environment:
      PORT: 4000
    command:
      - npm
      - run
      - live-reload
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 4000:4000

volumes:
  node_modules: {}